name: PSXFUNKIN BUILD?!?!?!

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build: [Debug, Release]
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Download PSn00bSDK
        uses: robinraju/release-downloader@main
        with: 
          repository: "UNSTOP4BLE/PSn00bSDK-kuseg"
          tag: "v0.24-kuseg"
          fileName: "PSn00bSDK-0.24-Linux.zip"
      - name: Compile
        run: |
          unzip -q PSn00bSDK-0.24-Linux.zip
          mv PSn00bSDK-0.24-Linux /opt/psn00bsdk
          export PATH=$PATH:/opt/psn00bsdk/bin
          export PSN00BSDK_LIBS=/opt/psn00bsdk/lib/libpsn00b
          sudo apt install libavformat-dev libswscale-dev
          sudo add-apt-repository ppa:savoury1/ffmpeg6
          sudo add-apt-repository ppa:savoury1/ffmpeg4
          sudo apt-get update
          sudo apt full-upgrade
          sudo apt install ffmpeg
          cmake -S ./tools -B ./tools/build -G "Ninja"
          cmake --build ./tools/build
          cmake -S . -B ./build -G "Ninja" -DCMAKE_TOOLCHAIN_FILE=/opt/psn00bsdk/lib/libpsn00b/cmake/sdk.cmake -DCMAKE_BUILD_TYPE=${{ matrix.build }}
          cmake --build ./build -j24
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: Funkin-${{ matrix.build }}
          path: |
            build/funkin.bin
            build/funkin.cue
